import type { Metadata } from "next";
import "./globals.css";
import ThemeProviderWrapper from "@/components/ThemeProvider";
import ProgressBar from "@/components/ProgressBarWrapper";
import { ToastContainer} from "react-toastify";
import localFont from "next/font/local"
import {GeistSans} from "geist/font/sans"
export const metadata: Metadata = {
  title: "Cafe - Home",
  description: "Generated by create next app",
  icons : {
    icon : "..//favicon.ico"
  }
};
const BlackSvaneExtaBoldItalic  = localFont({
  src : [
   {
    path : "../font/BlackSvan78uytte_eXtra_boldItalic986yyt.otf",
    weight: '400',
    style: 'normal'
   }
  ],
  variable : "--font-extrabold-savane",
  display : "fallback"
})
const BlackSvaneLightItalic  = localFont({
  src : [
   {
    path : "../font/Black_uorurSvaneuy6689cssdfLig__05034htItalic.otf",
    weight: '400',
    style: 'normal'
   }
  ],
  variable : "--font-lightitalic-savane",
  display : "fallback"
})
const brewFont = localFont({
  src : [
    {
      path : "../font/eldritchgdwwetTTcsx_6987vanguard.otf",
      weight : "400",
      style : "normal"
    }
  ],
  variable : "--font-brew-cafe",
  display : "swap"
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${BlackSvaneExtaBoldItalic.variable} ${brewFont.variable} ${BlackSvaneLightItalic.variable}`} suppressHydrationWarning={true}>
      <body className={`overflow-hidden`}>
       <ProgressBar>
          <ToastContainer theme="dark" autoClose={2000}/>
            <ThemeProviderWrapper>
            {children}
        </ThemeProviderWrapper>
       </ProgressBar>
      </body>
    </html>
  );
}
