import type { Metadata } from "next";
import "./globals.css";
import ThemeProviderWrapper from "@/components/ThemeProvider";
import ProgressBar from "@/components/ProgressBarWrapper";
import { ToastContainer} from "react-toastify";
import localFont from "next/font/local"
import { NextFont } from "next/dist/compiled/@next/font";
export const metadata: Metadata = {
  title: "Cafe - Home",
  description: "Generated by create next app",
  icons : {
    icon : "..//favicon.ico"
  }
};
const customFont : NextFont = localFont({
  src : [
   {
    path : "../font/f1eruntty_1778_xttmncff.woff2",
    weight: '400',
    style: 'normal'
   }
  ]
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${customFont.className} overflow-hidden`}>
       <ProgressBar>
          <ToastContainer theme="dark"/>
            <ThemeProviderWrapper>
            {children}
        </ThemeProviderWrapper>
       </ProgressBar>
      </body>
    </html>
  );
}
